#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-kaminari
Version  : 0.16.1
Release  : 4
URL      : https://rubygems.org/gems/kaminari-0.16.1.gem
Source0  : https://rubygems.org/gems/kaminari-0.16.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-actionpack
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-capybara
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rr
BuildRequires : rubygem-rspec
BuildRequires : rubygem-tzinfo

%description
= Kaminari {<img src="https://travis-ci.org/amatsuda/kaminari.svg"/>}[http://travis-ci.org/amatsuda/kaminari] {<img src="https://img.shields.io/codeclimate/github/amatsuda/kaminari.svg" />}[https://codeclimate.com/github/amatsuda/kaminari] {<img src="http://inch-ci.org/github/amatsuda/kaminari.svg" alt="Inline docs" />}[http://inch-ci.org/github/amatsuda/kaminari]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n kaminari-0.16.1
gem spec %{SOURCE0} -l --ruby > rubygem-kaminari.gemspec

%build
gem build rubygem-kaminari.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
kaminari-0.16.1.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/kaminari-0.16.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActionViewExtension/cdesc-ActionViewExtension.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActionViewExtension/link_to_next_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActionViewExtension/link_to_previous_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActionViewExtension/page_entries_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActionViewExtension/paginate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActionViewExtension/rel_next_prev_link_tags-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActiveRecordExtension/ActiveRecord/cdesc-ActiveRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActiveRecordExtension/cdesc-ActiveRecordExtension.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActiveRecordModelExtension/cdesc-ActiveRecordModelExtension.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActiveRecordRelationMethods/ActiveRecord/VERSION/cdesc-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActiveRecordRelationMethods/ActiveRecord/cdesc-ActiveRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActiveRecordRelationMethods/cdesc-ActiveRecordRelationMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ActiveRecordRelationMethods/entry_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Configuration/cdesc-Configuration.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/ClassMethods/default_per_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/ClassMethods/max_pages-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/ClassMethods/max_pages_per-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/ClassMethods/max_paginates_per-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/ClassMethods/max_per_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/ClassMethods/paginates_per-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/ConfigurationMethods/cdesc-ConfigurationMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperCollectionMethods/cdesc-DataMapperCollectionMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperCollectionMethods/entry_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Collection/cdesc-Collection.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Model/cdesc-Model.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Model/limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Model/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Paginatable/cdesc-Paginatable.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Paginating/all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Paginating/cdesc-Paginating.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/Paginating/per-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/DataMapperExtension/cdesc-DataMapperExtension.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Engine/cdesc-Engine.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/ConfigGenerator/cdesc-ConfigGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/ConfigGenerator/copy_config_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/GitHubApiHelper/cdesc-GitHubApiHelper.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/GitHubApiHelper/get_content_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/GitHubApiHelper/get_content_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/GitHubApiHelper/get_files_in_master-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/GitHubApiHelper/get_files_in_master-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/Theme/cdesc-Theme.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/Theme/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/ViewsGenerator/cdesc-ViewsGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/ViewsGenerator/copy_default_views-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/ViewsGenerator/download_templates-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/ViewsGenerator/template_engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/ViewsGenerator/themes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/FirstPage/cdesc-FirstPage.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Gap/cdesc-Gap.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/LastPage/cdesc-LastPage.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Link/cdesc-Link.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Link/page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Link/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/NextPage/cdesc-NextPage.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Page/cdesc-Page.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Page/page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/%2b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/%2d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/cdesc-PageProxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/current%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/first%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/inside_window%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/last%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/left_outer%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/next%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/number-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/prev%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/right_outer%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/to_i-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/PageProxy/was_truncated%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/cdesc-Paginator.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/each_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/each_relevant_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/page_tag-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/relevant_pages-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Paginator/subscriber/cdesc-subscriber.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/PrevPage/cdesc-PrevPage.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelper/cdesc-SinatraHelper.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelper/registered-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/ActionViewTemplateProxy/cdesc-ActionViewTemplateProxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/ActionViewTemplateProxy/link_to_unless-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/ActionViewTemplateProxy/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/ActionViewTemplateProxy/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/ActionViewTemplateProxy/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/ActionViewTemplateProxy/url_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/HelperMethods/cdesc-HelperMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/HelperMethods/link_to_next_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/HelperMethods/link_to_previous_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/HelperMethods/paginate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/cdesc-SinatraHelpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/registered-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/SinatraHelpers/view_paths-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Tag/cdesc-Tag.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Tag/page_url_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/Tag/partial_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Helpers/cdesc-Helpers.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Hooks/cdesc-Hooks.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Hooks/init-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/MongoMapperExtension/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/MongoMapperExtension/cdesc-MongoMapperExtension.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/MongoidCriteriaMethods/cdesc-MongoidCriteriaMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/MongoidCriteriaMethods/entry_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/MongoidCriteriaMethods/unpage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/MongoidExtension/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/MongoidExtension/cdesc-MongoidExtension.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/cdesc-PageScopeMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/current_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/first_page%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/last_page%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/next_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/num_pages-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/out_of_range%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/padding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/per-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/prev_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PageScopeMethods/total_pages-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PaginatableArray/cdesc-PaginatableArray.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PaginatableArray/entry_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PaginatableArray/limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PaginatableArray/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PaginatableArray/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PaginatableArray/total_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PluckyCriteriaMethods/cdesc-PluckyCriteriaMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/PluckyCriteriaMethods/entry_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/cdesc-Kaminari.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/config-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/configure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/Kaminari/paginate_array-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/kaminari-0.16.1/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/.document
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/.gemtest
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/CHANGELOG.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_first_page.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_first_page.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_first_page.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_gap.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_gap.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_gap.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_last_page.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_last_page.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_last_page.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_next_page.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_next_page.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_next_page.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_page.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_page.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_page.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_paginator.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_paginator.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_paginator.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_prev_page.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_prev_page.html.haml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/app/views/kaminari/_prev_page.html.slim
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/config/locales/kaminari.yml
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/active_record_30.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/active_record_31.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/active_record_32.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/active_record_40.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/active_record_41.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/active_record_edge.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/data_mapper_12.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/mongo_mapper.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/mongoid_24.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/mongoid_30.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/mongoid_31.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/mongoid_40.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/sinatra_13.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/gemfiles/sinatra_14.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/kaminari.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/generators/kaminari/config_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/generators/kaminari/templates/kaminari_config.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/generators/kaminari/views_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/engine.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/grape.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/helpers/action_view_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/helpers/paginator.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/helpers/sinatra_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/helpers/tags.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/hooks.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/active_record_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/active_record_model_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/active_record_relation_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/array_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/configuration_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/data_mapper_collection_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/data_mapper_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/mongo_mapper_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/mongoid_criteria_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/mongoid_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/page_scope_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/models/plucky_criteria_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/railtie.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/sinatra.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/lib/kaminari/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/config/config_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/active_record/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/active_record/models.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/data_mapper/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/data_mapper/models.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/mongo_mapper/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/mongo_mapper/models.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/mongoid/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/mongoid/models.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/rails_app.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/sinatra_app.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/views/alternative/kaminari/_first_page.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/views/alternative/kaminari/_paginator.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/views/kaminari/bootstrap/_page.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_app/views/kaminari/bootstrap/_paginator.html.erb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/fake_gem.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/generators/views_generator_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/helpers/action_view_extension_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/helpers/helpers_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/helpers/sinatra_helpers_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/helpers/tags_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/models/active_record/active_record_relation_methods_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/models/active_record/scopes_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/models/array_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/models/configuration_methods_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/models/data_mapper/data_mapper_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/models/mongo_mapper/mongo_mapper_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/models/mongoid/mongoid_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/requests/users_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/spec_helper_for_sinatra.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/support/database_cleaner.rb
/usr/lib64/ruby/gems/2.2.0/gems/kaminari-0.16.1/spec/support/matchers.rb
/usr/lib64/ruby/gems/2.2.0/specifications/kaminari-0.16.1.gemspec
